version: "3.2"

services:
  rabbit_mq:
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  producer:
    build: producer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        EXCHANGER_NAME: "msg"
        PUBLICATIONS_COUNT: 3
    volumes:
      - ./producer:/home/da/prog/broker/rabbit/producer

  consumer1:
    build: consumer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        EXCHANGER_NAME: "msg"
    volumes:
      - ./consumer:/home/da/prog/broker/rabbit/consumer

  consumer2:
    build: consumer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
        EXCHANGER_NAME: "msg"
    volumes:
       - ./consumer:/home/da/prog/broker/rabbit/consumer
volumes:
    rabbit_mqdata:
      driver: local

